# Numpy : 
numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB.

In [2]:
import numpy as np

## Creating NumPy Arrays : 
array is created by input a list 

In [4]:
lis = [1,13,4,5,6]
arr = np.array(lis)
arr

array([ 1, 13,  4,  5,  6])

## built in methods

### - arange --->  np.arrange (begin, end, step)

In [7]:
arr0 = np.arange(0,5,0.5)
arr0

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

### - zeros, ones and eye ---> np.zeros-or ones or eye-((raws,cols))

In [23]:
print("zeros with one input : \n",np.zeros(4))
print("two inputs must be tuple : \n",np.ones((3,3)))
print("eye take tuple : \n",np.eye(3))

zeros with one input : 
 [ 0.  0.  0.  0.]
two inputs must be tuple : 
 [[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
eye take tuple : 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


### - linspace ---> np.linspace(begin, end, n_points)

In [33]:
np.linspace(0,8,10)

array([ 0.        ,  0.88888889,  1.77777778,  2.66666667,  3.55555556,
        4.44444444,  5.33333333,  6.22222222,  7.11111111,  8.        ])

### - Random ---> np.random.rand(raws, cols)

In [35]:
print("one input : \n", np.random.rand(3))
print("two inputs : \n", np.random.rand(3,2))

one input : 
 [ 0.62017615  0.05838609  0.34618242]
two inputs : 
 [[ 0.65721728  0.27874709]
 [ 0.11563277  0.11431658]
 [ 0.51634158  0.71687899]]


### - reshape ---> arr.reshape(raws,cols) : cols*raws must be constant after and before every reshaping

In [45]:
arr1 = arr0.reshape(2,5)
arr1

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5]])

###  - appending 

#### + appending vertically

In [73]:
np.vstack((arr1, [4, 5, 6, 7,6]))

array([[ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5],
       [ 4. ,  5. ,  6. ,  7. ,  6. ]])

#### - appending horizontally

In [75]:
np.hstack((arr1, [[10], [10]]))

array([[  0. ,   0.5,   1. ,   1.5,   2. ,  10. ],
       [  2.5,   3. ,   3.5,   4. ,   4.5,  10. ]])

### - dtype ---> arr.dtype : returns the type of the array


## Indexing

In [65]:
print("return one element",arr0[1])
print("return sequence : ",arr0[1:4])
print("return one element in 2d array : ",arr1[1,3])
print("return sequence : in 2d array : \n",arr1[0:2,1:3])

return one element 0.5
return sequence :  [ 0.5  1.   1.5]
return one element in 2d array :  4.0
return sequence : in 2d array : 
 [[ 0.5  1. ]
 [ 3.   3.5]]


### - Selection ---> arr(condtion)  : returns only array true elements

In [70]:
arr0[arr0>2]

array([ 2.5,  3. ,  3.5,  4. ,  4.5])

## Numpy Operations

In [71]:
arr2 = np.array([2,3,4,5,5,4])
arr3 = np.array([3,5,6,7,7,6])
arr2*arr3            # element wise multiplication
np.dot(arr2,arr3)    # dot product of vectors ot matrices
arr2/arr3        
np.sqrt(arr2)
np.sin(arr3)
np.exp(arr2)

array([   7.3890561 ,   20.08553692,   54.59815003,  148.4131591 ,
        148.4131591 ,   54.59815003])